### ISSUE TITLE
Suggestion: Use Homebrew / Linuxbrew for installation

### ISSUE THREAD

**Issue by khoegenauer** [karel-brinda/smbl#16]
This appears to be a direction that the Galaxy project is working toward. (https://trello.com/c/YmIBHyxm/2055-brew-module-installer, https://github.com/platform-brew/platform-brew) Seems time would be more productively spent writing formulas for a common package manager, rather than everybody doing their own thing. Wider adoption, less maintenance / duplication of effort, and whatnot. You'd lose support for Windows; but, given the easy use of Ubuntu VMs and the prevalence of Unix-only bio software, that isn't necessarily a bad thing.

**Comment by karel-brinda** [comment]
Dear Kevin,

thank you very much for your feedback. I was thinking about your idea for few months. I also did some testing with Brew on several computers. Brew (Science) seems to work well on OS X but I have been experiencing great difficulties on Linux. For sure it is a great project and I like it but I don't see how to incorporate it easily into SMBL such that compilation of at least SamTools, BWA, etc. would work everywhere without need of installation of any special software.

SMBL aims at situations when someone wants to use some of basic bioinformatics programs in a Snakemake pipeline and wants to ensure presence of those programs on user's computer (typical situation: script for a supervisor/student). The only prerequisite are SMBL (which can be installed together will Snakemake by `pip3 install smbl`) and few programs (GCC, Git, etc.) which should be present on any Unix machine.

I do not plan to spend much time by adding new formulas (as for example people in the Brew Science project do and I am grateful to them for it). I am aware of limitations of SMBL and I add mainly those programs that I use in my own projects.
